name: brac_arna
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter_svg: ^0.23.0+1
  get_storage: ^2.0.3
  flutter_spinkit: ^5.1.0
  google_fonts: ^2.0.0
  simple_animations: ^1.3.3
  dropdown_search: ^2.0.1
  sqflite: ^2.0.2
  flutter_offline: ^2.0.0
  http: ^0.13.4
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  path_provider: ^2.0.9
  image_picker: 0.7.4
  image_cropper: ^1.4.1
  flutter_image_compress: ^1.1.0
  url_launcher: ^6.0.20
  syncfusion_flutter_pdfviewer: ^19.4.56-beta
  uuid: ^3.0.6
  intl: ^0.17.0
  date_format: ^2.0.5
  flutter_share: ^2.0.0
  geolocator: ^7.7.1
  geocoding: ^2.0.1
  loading_overlay: ^0.3.0
  fl_chart: ^0.50.1
  getwidget: ^2.0.4

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_maps_flutter: ^2.1.3

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.0
  hive_generator: ^1.1.0

flutter:
  uses-material-design: true



  assets:
    - assets/
    - asset/
    - assets/images/
    - assets/locales/
    - assets/place/

